### ISSUE TITLE
这是病毒，真无语啊

### ISSUE THREAD

**Issue by zeroc2537** [SecurityNo1/Gh0st2023#10]
还删issue

**Comment by SecurityNo1** [comment]
已经说明了，我们没有删除任何issue,我们将已解决和不需要处理的issue关闭了

**Comment by Lay0us1** [comment]
![image](https://user-images.githubusercontent.com/99304369/224213307-4a08619f-4646-4d13-a1d9-dd2f6f945299.png)

**Comment by SecurityNo1** [comment]
客户端报毒不影响正常使用，请放心
