### ISSUE TITLE
生成客户端文件操作错误

### ISSUE THREAD

**Issue by hnximi** [SecurityNo1/Gh0st2023#3]
生成客户端文件操作错误，是什么原因

**Comment by Wh7t3zZ** [comment]
同问题

**Comment by chz2008** [comment]
放出来的，是有问题的，我测试的时候，也是有同样的问题。

**Comment by SecurityNo1** [comment]
核心客户端是的DLL文件，需要自己编译loader去执行dll即可，没有上传loder.exe，留够了足够的可修改空间
这套源码的确是从CcRemote改的，请认真阅读代码；
