### ISSUE TITLE
strFile = strCurrentPath + "\\server\\loder.exe";   //得到当前未处理文件名

### ISSUE THREAD

**Issue by chz2008** [SecurityNo1/Gh0st2023#4]
strFile = strCurrentPath + "\\server\\loder.exe";   //得到当前未处理文件名
莫名其妙的一句，包里面有吗？

**Comment by SecurityNo1** [comment]
核心客户端是的DLL文件，需要自己编译loader去执行dll即可，没有上传loder.exe，留够了足够的可修改空间
这套源码的确是从CcRemote改的，请认真阅读代码；
