### ISSUE TITLE
无法五大

### ISSUE THREAD

**Issue by chz2008** [SecurityNo1/Gh0st2023#5]
测试的时候  只能是127.0.0.1上线

**Comment by SecurityNo1** [comment]
是不是没有关闭控制端的windows防火墙

**Comment by chz2008** [comment]
应该是你们改写了loader吧  原始的不行，而你们有没有公布loader源码，我找了一个其他开源的，谢谢

**Comment by chz2008** [comment]
https://github.com/Cc28256/CcRemote/   看人家的原版吧   我对比了一下代码 除了注释人家几个东西   啥也没改
